In [8]:
import pandas as pd 
import numpy as np
import streamlit as st
import matplotlib.pyplot as plt
import os

In [9]:
df=pd.read_csv("C:/Users/arunm/Downloads/combined_stock_data.csv")

In [10]:
df

,Ticker,close,date,high,low,month,open,volume
0,EICHERMOT,3351.40,2023-10-03 05:30:00,3434.95,3302.90,2023-10,3426.90,1354075
1,EICHERMOT,3400.90,2023-10-04 05:30:00,3408.95,3323.75,2023-10,3350.00,566983
2,EICHERMOT,3443.60,2023-10-05 05:30:00,3453.90,3387.05,2023-10,3405.50,394665
3,EICHERMOT,3450.40,2023-10-06 05:30:00,3464.45,3438.35,2023-10,3443.60,249258
4,EICHERMOT,3445.60,2023-10-09 05:30:00,3476.00,3401.00,2023-10,3420.20,471285
...,...,...,...,...,...,...,...,...
14195,POWERGRID,312.10,2024-11-14 05:30:00,318.80,310.60,2024-11,315.10,12500377
14196,POWERGRID,312.05,2024-11-18 05:30:00,315.55,310.10,2024-11,314.00,9408101
14197,POWERGRID,315.05,2024-11-19 05:30:00,318.25,312.25,2024-11,313.05,13157158
14198,POWERGRID,325.90,2024-11-21 05:30:00,326.75,313.00,2024-11,316.00,25406386
14199,POWERGRID,336.95,2024-11-22 05:30:00,337.60,324.00,2024-11,325.80,31523269

In [11]:
df["date"] = pd.to_datetime(df["date"])
df = df.sort_values(["Ticker", "date"])

In [12]:
df.isnull().sum()

Ticker    0
close     0
date      0
high      0
low       0
month     0
open      0
volume    0
dtype: int64

In [13]:
df.duplicated().sum()

np.int64(0)

In [14]:
df.describe()

,close,date,high,low,open,volume
count,14200.000000,14200,14200.000000,14200.000000,14200.000000,1.420000e+04
mean,2449.415380,2024-04-27 20:17:19.436619776,2476.495940,2422.374544,2450.982693,6.833475e+06
min,116.600000,2023-10-03 05:30:00,118.550000,114.600000,114.600000,5.987000e+03
25%,821.850000,2024-01-14 11:30:00,831.900000,814.500000,824.775000,9.636955e+05
50%,1508.175000,2024-04-29 17:30:00,1523.875000,1493.315000,1510.000000,2.446882e+06
75%,3101.762500,2024-08-09 23:30:00,3138.150000,3066.062500,3101.837500,8.592909e+06
max,13495.600000,2024-11-22 05:30:00,13680.000000,13274.450000,13393.000000,2.680527e+08
std,2573.791109,NaN,2601.744121,2545.346794,2575.276197,1.129303e+07

In [15]:
df.sample(50).info()

<class 'pandas.core.frame.DataFrame'>
Index: 50 entries, 12960 to 2578
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Ticker  50 non-null     object
 1   close   50 non-null     float64
 2   date    50 non-null     datetime64[ns]
 3   high    50 non-null     float64
 4   low     50 non-null     float64
 5   month   50 non-null     object
 6   open    50 non-null     float64
 7   volume  50 non-null     int64
dtypes: datetime64[ns](1), float64(4), int64(1), object(2)
memory usage: 3.5+ KB

In [16]:
df.dtypes

Ticker            object
close            float64
date      datetime64[ns]
high             float64
low              float64
month             object
open             float64
volume             int64
dtype: object

In [17]:
numeric_cols = ['open', 'high', 'low', 'close', 'volume']
df[numeric_cols] = df[numeric_cols].apply(pd.to_numeric)

In [18]:
df["Daily_Return"] = df.groupby("Ticker")["close"].pct_change()
df["Daily_Return"]

11644         NaN
11645    0.032548
11646    0.000568
11647    0.004764
11648   -0.014325
           ...
10219   -0.004042
10220   -0.024440
10221    0.016551
10222   -0.008630
10223    0.026025
Name: Daily_Return, Length: 14200, dtype: float64

In [19]:
df["Cumulative_Return"] = (1 + df["Daily_Return"]).groupby(df["Ticker"]).cumprod()
df["Cumulative_Return"]

11644         NaN
11645    1.032548
11646    1.033134
11647    1.038056
11648    1.023186
           ...
10219    1.397706
10220    1.363547
10221    1.386114
10222    1.374152
10223    1.409915
Name: Cumulative_Return, Length: 14200, dtype: float64

In [20]:
df["Month"] = df["date"].dt.to_period("M")

In [21]:
df["Month"]

11644    2023-10
11645    2023-10
11646    2023-10
11647    2023-10
11648    2023-10
          ...
10219    2024-11
10220    2024-11
10221    2024-11
10222    2024-11
10223    2024-11
Name: Month, Length: 14200, dtype: period[M]

In [22]:
sector_df = pd.read_csv("C:/Users/arunm/Downloads/Sector_data - Sheet1.csv")

In [23]:
sector_df.head()

             COMPANY         sector                         Symbol
0  ADANI ENTERPRISES  MISCELLANEOUS  ADANI ENTERPRISES: ADANIGREEN
1  ADANI PORTS & SEZ  MISCELLANEOUS  ADANI PORTS & SEZ: ADANIPORTS
2   APOLLO HOSPITALS  MISCELLANEOUS   APOLLO HOSPITALS: APOLLOHOSP
3       ASIAN PAINTS         PAINTS       ASIAN PAINTS: ASIANPAINT
4          AXIS BANK        BANKING            AXIS BANK: AXISBANK

In [24]:
sector_df["Symbol"] = sector_df["Symbol"].str.split(":").str[1].str.strip()

In [25]:
sector_df["Symbol"]

0       ADANIGREEN
1       ADANIPORTS
2       APOLLOHOSP
3       ASIANPAINT
4         AXISBANK
5       BAJAJ-AUTO
6       BAJFINANCE
7       BAJAJFINSV
8              BEL
9           AIRTEL
10            BPCL
11           CIPLA
12       COALINDIA
13         DRREDDY
14       EICHERMOT
15          GRASIM
16         HCLTECH
17        HDFCBANK
18        HDFCLIFE
19      HEROMOTOCO
20        HINDALCO
21      HINDUNILVR
22       ICICIBANK
23      INDUSINDBK
24            INFY
25             IOC
26             ITC
27        JSWSTEEL
28       KOTAKBANK
29              LT
30             M&M
31          MARUTI
32       NESTLEIND
33            NTPC
34            ONGC
35       POWERGRID
36        RELIANCE
37            SBIN
38         SBILIFE
39      SHRIRAMFIN
40       SUNPHARMA
41    TATACONSUMER
42      TATAMOTORS
43       TATASTEEL
44             TCS
45           TECHM
46           TITAN
47           TRENT
48      ULTRACEMCO
49           WIPRO
Name: Symbol, dtype: object

In [26]:
df = df.merge(
        sector_df[["Symbol", "sector"]],
        left_on="Ticker",
        right_on="Symbol",
        how="left"
)

df.drop(columns="Symbol", inplace=True)

In [27]:
yearly_return = (
    df.groupby("Ticker")["Cumulative_Return"]
      .last()
      .reset_index()
      .rename(columns={"Cumulative_Return":"Yearly_Return"})
)

In [28]:
yearly_return.head()

       Ticker  Yearly_Return
0    ADANIENT       0.933291
1  ADANIPORTS       1.367272
2  APOLLOHOSP       1.354790
3  ASIANPAINT       0.780650
4    AXISBANK       1.097354

In [29]:
os.makedirs("outputs", exist_ok=True)

top_green = yearly_return.sort_values("Yearly_Return", ascending=False).head(10)
top_green.to_csv("top10_green.csv", index=False)

In [30]:
top_green

        Ticker  Yearly_Return
47       TRENT       3.230926
8          BEL       2.017601
30         M&M       1.959770
5   BAJAJ-AUTO       1.890112
9   BHARTIARTL       1.695990
35   POWERGRID       1.688549
10        BPCL       1.674772
20  HEROMOTOCO       1.589767
40   SUNPHARMA       1.572824
17     HCLTECH       1.532574

In [31]:
top_red = yearly_return.sort_values("Yearly_Return").head(10)
top_red.to_csv("outputs/top10_red.csv", index=False)

In [32]:
top_red

        Ticker  Yearly_Return
24  INDUSINDBK       0.695416
3   ASIANPAINT       0.780650
7   BAJFINANCE       0.838891
0     ADANIENT       0.933291
22  HINDUNILVR       0.990421
32   NESTLEIND       1.007071
28   KOTAKBANK       1.019918
6   BAJAJFINSV       1.025496
46       TITAN       1.035182
31      MARUTI       1.069267

In [33]:
total = yearly_return.shape[0]

green = (yearly_return["Yearly_Return"] > 1).sum()
red   = (yearly_return["Yearly_Return"] < 1).sum()

market_summary = {
    "Total Stocks": total,
    "Green Stocks": green,
    "Red Stocks": red,
    "Green (%)": round(green/total*100,2)
}

market_summary

{'Total Stocks': 50,
 'Green Stocks': np.int64(45),
 'Red Stocks': np.int64(5),
 'Green (%)': np.float64(90.0)}

In [34]:
avg_price = df.groupby("Ticker")["close"].mean().mean()

avg_volume = df.groupby("Ticker")["volume"].mean().mean()

print("Avg Price:", avg_price)
print("Avg Volume:", avg_volume)

Avg Price: 2449.4153795774646
Avg Volume: 6833474.6491549285

In [35]:
vol = (
    df.groupby("Ticker")["Daily_Return"]
      .std()
      .reset_index()
      .rename(columns={"Daily_Return":"Volatility"})
      .sort_values("Volatility", ascending=False)
)

vol.to_csv("outputs/volatility.csv", index=False)
vol.head()

        Ticker  Volatility
0     ADANIENT    0.028601
1   ADANIPORTS    0.026029
8          BEL    0.023283
47       TRENT    0.023074
34        ONGC    0.022247

In [36]:
cum = df.groupby(["Ticker","date"])["Cumulative_Return"].last().reset_index()
cum.to_csv("outputs/cumulative_returns.csv", index=False)
cum.head()

     Ticker                date  Cumulative_Return
0  ADANIENT 2023-10-03 05:30:00                NaN
1  ADANIENT 2023-10-04 05:30:00           1.032548
2  ADANIENT 2023-10-05 05:30:00           1.033134
3  ADANIENT 2023-10-06 05:30:00           1.038056
4  ADANIENT 2023-10-09 05:30:00           1.023186

In [37]:
sector_perf = df.groupby("sector")["Cumulative_Return"].last()

sector_perf = sector_perf.reset_index()
sector_perf.columns = ["Sector", "Avg_Yearly_Return"]

sector_perf.to_csv("outputs/sector_performance.csv", index=False)
sector_perf.head()

        Sector  Avg_Yearly_Return
0    ALUMINIUM           1.358683
1  AUTOMOBILES           1.274881
2      BANKING           1.353429
3       CEMENT           1.369709
4      DEFENCE           2.017601

In [38]:
pivot = df.pivot(index="date", columns="Ticker", values="close")

corr = pivot.corr()

corr.to_csv("outputs/correlation_matrix.csv")
corr.head()

Ticker,ADANIENT,ADANIPORTS,APOLLOHOSP,ASIANPAINT,AXISBANK,BAJAJ-AUTO,BAJAJFINSV,BAJFINANCE,BEL,BHARTIARTL,...,SUNPHARMA,TATACONSUM,TATAMOTORS,TATASTEEL,TCS,TECHM,TITAN,TRENT,ULTRACEMCO,WIPRO
Ticker,,,,,,,,,,,,,,,,,,,,,
ADANIENT,1.000000,0.845806,0.594807,-0.186479,0.537048,0.634551,0.080113,-0.437309,0.597634,0.482298,...,0.555206,0.783299,0.783965,0.732033,0.601375,0.306188,0.457118,0.436790,0.590462,0.609774
ADANIPORTS,0.845806,1.000000,0.815085,-0.246520,0.770207,0.887718,0.215085,-0.486128,0.900377,0.819970,...,0.833258,0.823057,0.916523,0.834255,0.817482,0.659344,0.215162,0.779358,0.855521,0.798804
APOLLOHOSP,0.594807,0.815085,1.000000,-0.157872,0.607392,0.893753,0.509150,-0.410892,0.752139,0.865525,...,0.948026,0.668899,0.687952,0.520929,0.861910,0.849917,0.268920,0.877633,0.830027,0.906900
ASIANPAINT,-0.186479,-0.246520,-0.157872,1.000000,0.000971,-0.162563,0.463444,0.609427,-0.246263,-0.178033,...,-0.210304,-0.005593,-0.247491,-0.357433,-0.038384,-0.030905,0.370942,-0.093118,0.017379,-0.230921
AXISBANK,0.537048,0.770207,0.607392,0.000971,1.000000,0.742850,0.334558,-0.155250,0.863011,0.767627,...,0.620854,0.531076,0.596831,0.709668,0.596471,0.681483,0.002643,0.735466,0.867694,0.674543

In [39]:
monthly = (
    df.groupby(["Ticker","Month"])["Cumulative_Return"]
      .last()
      .groupby("Month")
      .apply(lambda x: x.sort_values(ascending=False))
)

for m in monthly.index.levels[0]:
    month_data = monthly.loc[m]
    winners = month_data.head(5)
    losers  = month_data.tail(5)
    print(f"\nMONTH: {m}")
    print("TOP 5 GAINERS")
    print(winners)
    print("TOP 5 LOSERS")
    print(losers)

MONTH: 2023-10
TOP 5 GAINERS
Ticker      Month
NESTLEIND   2023-10    1.086022
COALINDIA   2023-10    1.076567
BAJAJ-AUTO  2023-10    1.059325
SBILIFE     2023-10    1.058339
TRENT       2023-10    1.046428
Name: Cumulative_Return, dtype: float64
TOP 5 LOSERS
Ticker      Month
APOLLOHOSP  2023-10    0.941580
BAJFINANCE  2023-10    0.940390
SBIN        2023-10    0.937972
TECHM       2023-10    0.931714
TATASTEEL   2023-10    0.927734
Name: Cumulative_Return, dtype: float64

MONTH: 2023-11
TOP 5 GAINERS
Ticker      Month
TRENT       2023-11    1.353504
BPCL        2023-11    1.276365
HEROMOTOCO  2023-11    1.266431
BAJAJ-AUTO  2023-11    1.214116
COALINDIA   2023-11    1.172148
Name: Cumulative_Return, dtype: float64
TOP 5 LOSERS
Ticker      Month
ITC         2023-11    0.991018
ADANIENT    2023-11    0.987978
ASIANPAINT  2023-11    0.985175
SBIN        2023-11    0.936645
BAJFINANCE  2023-11    0.893858
Name: Cumulative_Return, dtype: float64

MONTH: 2023-12
TOP 5 GAINERS
Ticker      Month
TRENT       2023-12    1.483634
HEROMOTOCO  2023-12    1.372712
BAJAJ-AUTO  2023-12    1.354992
BEL         2023-12    1.323276
BPCL        2023-12    1.320190
Name: Cumulative_Return, dtype: float64
TOP 5 LOSERS
Ticker      Month
ITC         2023-12    1.050824
TECHM       2023-12    1.046415
HDFCLIFE    2023-12    1.020756
MARUTI      2023-12    0.995690
BAJFINANCE  2023-12    0.919694
Name: Cumulative_Return, dtype: float64

MONTH: 2024-01
TOP 5 GAINERS
Ticker      Month
HEROMOTOCO  2024-01    1.532547
BAJAJ-AUTO  2024-01    1.528481
TRENT       2024-01    1.499174
BPCL        2024-01    1.471643
ADANIPORTS  2024-01    1.452550
Name: Cumulative_Return, dtype: float64
TOP 5 LOSERS
Ticker      Month
MARUTI      2024-01    0.984536
HDFCBANK    2024-01    0.969829
ASIANPAINT  2024-01    0.934004
HDFCLIFE    2024-01    0.910110
BAJFINANCE  2024-01    0.861351
Name: Cumulative_Return, dtype: float64

MONTH: 2024-02
TOP 5 GAINERS
Ticker      Month
TRENT       2024-02    1.885193
BPCL        2024-02    1.768983
ADANIPORTS  2024-02    1.588285
BAJAJ-AUTO  2024-02    1.576683
TATAMOTORS  2024-02    1.531469
Name: Cumulative_Return, dtype: float64
TOP 5 LOSERS
Ticker      Month
HDFCBANK    2024-02    0.930606
ITC         2024-02    0.923934
HDFCLIFE    2024-02    0.918633
ASIANPAINT  2024-02    0.891075
BAJFINANCE  2024-02    0.815220
Name: Cumulative_Return, dtype: float64

MONTH: 2024-03
TOP 5 GAINERS
Ticker      Month
TRENT       2024-03    1.917343
BAJAJ-AUTO  2024-03    1.823630
BPCL        2024-03    1.764706
ADANIPORTS  2024-03    1.613964
TATAMOTORS  2024-03    1.600129
Name: Cumulative_Return, dtype: float64
TOP 5 LOSERS
Ticker      Month
ITC         2024-03    0.974076
HDFCBANK    2024-03    0.960114
HINDUNILVR  2024-03    0.917149
BAJFINANCE  2024-03    0.909339
ASIANPAINT  2024-03    0.898922
Name: Cumulative_Return, dtype: float64

MONTH: 2024-04
TOP 5 GAINERS
Ticker      Month
TRENT       2024-04    2.141664
BPCL        2024-04    1.779236
BAJAJ-AUTO  2024-04    1.774891
BEL         2024-04    1.679239
TATAMOTORS  2024-04    1.624466
Name: Cumulative_Return, dtype: float64
TOP 5 LOSERS
Ticker      Month
KOTAKBANK   2024-04    0.940303
HDFCLIFE    2024-04    0.921237
ASIANPAINT  2024-04    0.908126
HINDUNILVR  2024-04    0.903419
BAJFINANCE  2024-04    0.868963
Name: Cumulative_Return, dtype: float64

MONTH: 2024-05
TOP 5 GAINERS
Ticker      Month
TRENT       2024-05    2.214147
BEL         2024-05    2.126078
BPCL        2024-05    1.839114
BAJAJ-AUTO  2024-05    1.810992
ADANIPORTS  2024-05    1.728891
Name: Cumulative_Return, dtype: float64
TOP 5 LOSERS
Ticker      Month
ITC         2024-05    0.969756
HINDUNILVR  2024-05    0.943355
ASIANPAINT  2024-05    0.909800
HDFCLIFE    2024-05    0.867887
BAJFINANCE  2024-05    0.840617
Name: Cumulative_Return, dtype: float64

MONTH: 2024-06
TOP 5 GAINERS
Ticker      Month
TRENT       2024-06    2.661284
BEL         2024-06    2.197557
BAJAJ-AUTO  2024-06    1.894098
M&M         2024-06    1.864609
HEROMOTOCO  2024-06    1.850245
Name: Cumulative_Return, dtype: float64
TOP 5 LOSERS
Ticker      Month
HINDUNILVR  2024-06    1.001681
ITC         2024-06    0.966231
HDFCLIFE    2024-06    0.939231
ASIANPAINT  2024-06    0.921120
BAJFINANCE  2024-06    0.893061
Name: Cumulative_Return, dtype: float64

MONTH: 2024-07
TOP 5 GAINERS
Ticker      Month
TRENT       2024-07    2.835705
BEL         2024-07    2.270474
BPCL        2024-07    2.050914
BAJAJ-AUTO  2024-07    1.926502
M&M         2024-07    1.891375
Name: Cumulative_Return, dtype: float64
TOP 5 LOSERS
Ticker      Month
BAJAJFINSV  2024-07    1.058038
KOTAKBANK   2024-07    1.046814
INDUSINDBK  2024-07    0.994705
ASIANPAINT  2024-07    0.973980
BAJFINANCE  2024-07    0.854329
Name: Cumulative_Return, dtype: float64

MONTH: 2024-08
TOP 5 GAINERS
Ticker      Month
TRENT       2024-08    3.476640
BAJAJ-AUTO  2024-08    2.171167
BEL         2024-08    2.150144
BPCL        2024-08    2.095442
M&M         2024-08    1.824769
Name: Cumulative_Return, dtype: float64
TOP 5 LOSERS
Ticker      Month
HDFCBANK    2024-08    1.085441
KOTAKBANK   2024-08    1.031122
INDUSINDBK  2024-08    0.992929
ASIANPAINT  2024-08    0.987353
BAJFINANCE  2024-08    0.903679
Name: Cumulative_Return, dtype: float64

MONTH: 2024-09
TOP 5 GAINERS
Ticker      Month
TRENT       2024-09    3.678622
BAJAJ-AUTO  2024-09    2.461093
BPCL        2024-09    2.167506
BEL         2024-09    2.048132
M&M         2024-09    2.013074
Name: Cumulative_Return, dtype: float64
TOP 5 LOSERS
Ticker      Month
HDFCLIFE    2024-09    1.133297
KOTAKBANK   2024-09    1.073478
ASIANPAINT  2024-09    1.051234
INDUSINDBK  2024-09    1.008499
BAJFINANCE  2024-09    0.966791
Name: Cumulative_Return, dtype: float64

MONTH: 2024-10
TOP 5 GAINERS
Ticker      Month
TRENT       2024-10    3.461877
BEL         2024-10    2.046695
BAJAJ-AUTO  2024-10    1.960809
BPCL        2024-10    1.820659
M&M         2024-10    1.774782
Name: Cumulative_Return, dtype: float64
TOP 5 LOSERS
Ticker      Month
NESTLEIND   2024-10    1.014085
KOTAKBANK   2024-10    1.002345
ASIANPAINT  2024-10    0.926994
BAJFINANCE  2024-10    0.864721
INDUSINDBK  2024-10    0.735405
Name: Cumulative_Return, dtype: float64

MONTH: 2024-11
TOP 5 GAINERS
Ticker      Month
TRENT       2024-11    3.230926
BEL         2024-11    2.017601
M&M         2024-11    1.959770
BAJAJ-AUTO  2024-11    1.890112
BHARTIARTL  2024-11    1.695990
Name: Cumulative_Return, dtype: float64
TOP 5 LOSERS
Ticker      Month
HINDUNILVR  2024-11    0.990421
ADANIENT    2024-11    0.933291
BAJFINANCE  2024-11    0.838891
ASIANPAINT  2024-11    0.780650
INDUSINDBK  2024-11    0.695416
Name: Cumulative_Return, dtype: float64